import Head from 'next/head'

import Submit from '../components/Submit'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='my-4'>This is Pritish</h1>
      <Submit/>
    </div>
  )
}
